#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# shellcheck disable=SC2016,SC1091,SC2183

mkdir -p /config/wg_confs

# migration to subfolder for wg confs
if [[ -z "$(ls -A /config/wg_confs)" ]] && [[ -f /config/wg0.conf ]]; then
    echo "**** Performing migration to new folder structure for confs. Please see the image changelog 2023-10-03 entry for more details. ****"
    cp /config/wg0.conf /config/wg_confs/wg0.conf
    rm -rf /config/wg0.conf || :
fi

# prepare templates
if [[ ! -f /config/templates/server.conf ]]; then
    cp /defaults/server.conf /config/templates/server.conf
fi
if [[ ! -f /config/templates/peer.conf ]]; then
    cp /defaults/peer.conf /config/templates/peer.conf
fi
# add preshared key to user templates (backwards compatibility)
if ! grep -q 'PresharedKey' /config/templates/peer.conf; then
    sed -i 's|^Endpoint|PresharedKey = \$\(cat /config/\${PEER_ID}/presharedkey-\${PEER_ID}\)\nEndpoint|' /config/templates/peer.conf
fi

ip_version () {
    if [[ "$1" =~ : ]]; then
        echo 6
    elif [[ "$1" =~ \. ]]; then
        echo 4
    else
        echo 0
    fi
}

check_range() {
    local ip="$1"
    local start=$(echo "$2" | cut -d'-' -f1)
    local end=$(echo "$2" | cut -d'-' -f2)
    python3 - <<DUDE
import ipaddress, sys
ip = ipaddress.ip_address("$ip")
start = ipaddress.ip_address("$start")
end = ipaddress.ip_address("$end")
sys.exit(0 if start <= ip <= end else 1)
DUDE
    return $?
}

check_ranges () {
    local ip="$1"
    local ranges="$2"
    
    local version=$(ip_version "$ip")
    local ranges_array
    IFS=',' read -r -a ranges_array <<< "$ranges"
    local r
    for r in "${ranges_array[@]}"; do
        if [[ $version -ne $(ip_version "$r") ]]; then
            continue
        fi
        if check_range "$ip" "$r"; then
            return 0
        fi
    done
    return 1
}

allocate_ip () {
    local ranges_array
    IFS=',' read -r -a ranges_array <<< "$1"
    local r
    for r in "${ranges_array[@]}"; do
        local start=$(echo "$r" | cut -d'-' -f1)
        local end=$(echo "$r" | cut -d'-' -f2)
        local allocated_ip=$(python3 - <<DUDE
import ipaddress, glob, sys
start = ipaddress.ip_address("$start")
end = ipaddress.ip_address("$end")
ip = start
occupied = "$2".split(",") if "$2" else []
while ip <= end:
    if str(ip) not in occupied:
        print(str(ip))
        sys.exit(0)
    ip += 1
sys.exit(1)
DUDE
)
        if [[ $? -eq 0 ]]; then
            echo "$allocated_ip"
            return 0
        fi
    done
    echo "NONE"
}

extract_ranges_v() {
    local ranges_array
    IFS=',' read -r -a ranges_array <<< "$1"
    local r
    local result=""
    for r in "${ranges_array[@]}"; do
        if [[ $(ip_version "$r") -eq $2 ]]; then
            result="$result,$r"
        fi
    done
    # trim leading comma
    result="${result#,}"
    echo "$result"
}

generate_confs () {
    mkdir -p /config/server
    if [[ ! -f /config/server/privatekey-server ]]; then
        umask 077
        wg genkey | tee /config/server/privatekey-server | wg pubkey > /config/server/publickey-server
    fi
    eval "$(printf %s)
    cat <<DUDE > /config/wg_confs/wg0.conf
$(cat /config/templates/server.conf)

DUDE"
    OCCUPIED_IPS=""
    for i in "${PEERS_ARRAY[@]}"; do
        if [[ ! "${i}" =~ ^[[:alnum:]]+$ ]]; then
            echo "**** Peer ${i} contains non-alphanumeric characters and thus will be skipped. No config for peer ${i} will be generated. ****"
        else
            if [[ "${i}" =~ ^[0-9]+$ ]]; then
                PEER_ID="peer${i}"
            else
                PEER_ID="peer_${i}"
            fi
            if [[ -f "/config/${PEER_ID}/${PEER_ID}.conf" ]]; then
                CLIENT_IPS=$(grep "Address" "/config/${PEER_ID}/${PEER_ID}.conf" | awk -F'=' '{print $NF}' | tr -d ' ' | tr -d '\n' | tr -d '\r')
                OCCUPIED_IPS="$OCCUPIED_IPS,$CLIENT_IPS"
            fi
        fi
    done

    OCCUPIED_IPS="${OCCUPIED_IPS#,}" # trim leading comma

    for i in "${PEERS_ARRAY[@]}"; do
        if [[ ! "${i}" =~ ^[[:alnum:]]+$ ]]; then
            echo "**** Peer ${i} contains non-alphanumeric characters and thus will be skipped. No config for peer ${i} will be generated. ****"
        else
            if [[ "${i}" =~ ^[0-9]+$ ]]; then
                PEER_ID="peer${i}"
            else
                PEER_ID="peer_${i}"
            fi
            mkdir -p "/config/${PEER_ID}"
            if [[ ! -f "/config/${PEER_ID}/privatekey-${PEER_ID}" ]]; then
                umask 077
                wg genkey | tee "/config/${PEER_ID}/privatekey-${PEER_ID}" | wg pubkey > "/config/${PEER_ID}/publickey-${PEER_ID}"
                wg genpsk > "/config/${PEER_ID}/presharedkey-${PEER_ID}"
            fi
            if [[ -f "/config/${PEER_ID}/${PEER_ID}.conf" ]]; then
                CLIENT_IPS=$(grep "Address" "/config/${PEER_ID}/${PEER_ID}.conf" | awk -F'=' '{print $NF}' | tr -d ' ' | tr -d '\n' | tr -d '\r')
                CLIENT_IP=""
                IFS=',' read -r -a ip_array <<< "$CLIENT_IPS"

                local ip
                for ip in "${ip_array[@]}"; do
                    if [[ -z $(extract_ranges_v "$ALLOCATED_RANGES" $(ip_version "$ip") ) ]]; then
                        echo "**** Client IP $ip for peer ${PEER_ID} is removed because the same IP version is not present in the allocated ranges. ****"
                        ip=""
                        continue
                    fi
                    if ! check_ranges "$ip" "$ALLOCATED_RANGES"; then
                        echo "**** Client IP $ip for peer ${PEER_ID} is out of the allocated range $ALLOCATED_RANGES, allocating a new IP. ****"

                        ip=$(allocate_ip $(extract_ranges_v "$ALLOCATED_RANGES" $(ip_version "$ip")) "$OCCUPIED_IPS")
                        if [[ "$ip" = "NONE" ]]; then
                            echo "**** No available IPs in the allocated range $ALLOCATED_RANGES for peer ${PEER_ID}. Please expand the allocated range or remove some peers. ****"
                            exit 1
                        fi
                    fi
                    OCCUPIED_IPS="$OCCUPIED_IPS,$ip"
                    CLIENT_IP="$CLIENT_IP,$ip"
                done
                if [[ -n $(extract_ranges_v "$ALLOCATED_RANGES" 4) ]] && [[ -z $(extract_ranges_v "$CLIENT_IP" 4) ]]; then
                    echo "**** IPv4 was added to the allocated ranges, allocating an IPv4 for peer ${PEER_ID}. ****"
                    ip="$(allocate_ip $(extract_ranges_v "$ALLOCATED_RANGES" 4) "$OCCUPIED_IPS")"
                    if [[ "$CLIENT_IP" = *NONE* ]]; then
                        echo "**** No available IPv4s in the allocated range $ALLOCATED_RANGES for peer ${PEER_ID}. Skipping peer. ****"
                    else
                        CLIENT_IP="$CLIENT_IP,$ip"
                        OCCUPIED_IPS="$OCCUPIED_IPS,$ip"
                    fi
                fi
                if [[ -n $(extract_ranges_v "$ALLOCATED_RANGES" 6) ]] && [[ -z $(extract_ranges_v "$CLIENT_IP" 6) ]]; then
                    echo "**** IPv6 was added to the allocated ranges, allocating an IPv6 for peer ${PEER_ID}. ****"
                    ip="$(allocate_ip $(extract_ranges_v "$ALLOCATED_RANGES" 6) "$OCCUPIED_IPS")"
                    if [[ "$CLIENT_IP" = *NONE* ]]; then
                        echo "**** No available IPv6s in the allocated range $ALLOCATED_RANGES for peer ${PEER_ID}. Skipping peer. ****"
                    else
                        CLIENT_IP="$CLIENT_IP,$ip"
                        OCCUPIED_IPS="$OCCUPIED_IPS,$ip"
                    fi
                fi
                # trim leading comma
                CLIENT_IP="${CLIENT_IP#,}"
                # add space after each comma
                CLIENT_IP="${CLIENT_IP//,/, }"
            else
                # Check if there are ipv4 or ipv6 addresses in the allocated range and allocate accordingly
                CLIENT_IP=""
                local new_ip
                if [[ $(extract_ranges_v "$ALLOCATED_RANGES" 4) ]]; then
                    new_ip=$(allocate_ip $(extract_ranges_v "$ALLOCATED_RANGES" 4) "$OCCUPIED_IPS")
                    OCCUPIED_IPS="$OCCUPIED_IPS,$new_ip"
                    CLIENT_IP="$new_ip"
                fi
                if [[ $(extract_ranges_v "$ALLOCATED_RANGES" 6) ]]; then
                    new_ip="$(allocate_ip $(extract_ranges_v "$ALLOCATED_RANGES" 6) "$OCCUPIED_IPS")"
                    OCCUPIED_IPS="$OCCUPIED_IPS,$new_ip"
                    CLIENT_IP="$CLIENT_IP,$new_ip"
                fi

                if [[ $CLIENT_IP == *NONE* ]]; then
                    echo "**** No available IPs in the allocated range $ALLOCATED_RANGES for peer ${PEER_ID}. Please expand the allocated range or remove some peers. ****"
                    exit 1
                fi

                # trim leading comma
                CLIENT_IP="${CLIENT_IP#,}"
                # add space after each comma
                CLIENT_IP="${CLIENT_IP//,/, }"
            fi
            if [[ -f "/config/${PEER_ID}/presharedkey-${PEER_ID}" ]]; then
                # create peer conf with presharedkey
                eval "$(printf %s)
                cat <<DUDE > /config/${PEER_ID}/${PEER_ID}.conf
$(cat /config/templates/peer.conf)
DUDE"
                # add peer info to server conf with presharedkey
                cat <<DUDE >> /config/wg_confs/wg0.conf
[Peer]
# ${PEER_ID}
PublicKey = $(cat "/config/${PEER_ID}/publickey-${PEER_ID}")
PresharedKey = $(cat "/config/${PEER_ID}/presharedkey-${PEER_ID}")
DUDE
            else
                echo "**** Existing keys with no preshared key found for ${PEER_ID}, creating confs without preshared key for backwards compatibility ****"
                # create peer conf without presharedkey
                eval "$(printf %s)
                cat <<DUDE > /config/${PEER_ID}/${PEER_ID}.conf
$(sed '/PresharedKey/d' "/config/templates/peer.conf")
DUDE"
                # add peer info to server conf without presharedkey
                cat <<DUDE >> /config/wg_confs/wg0.conf
[Peer]
# ${PEER_ID}
PublicKey = $(cat "/config/${PEER_ID}/publickey-${PEER_ID}")
DUDE
            fi
            SERVER_ALLOWEDIPS=SERVER_ALLOWEDIPS_PEER_${i}
            local ip_list
            IFS=',' read -r -a ip_list <<< "${CLIENT_IP//, /,}"
            PALLOWEDIPS=""
            for ip in "${ip_list[@]}"; do
                if [[ $(ip_version "$ip") -eq 4 ]]; then
                    PALLOWEDIPS="${PALLOWEDIPS},${ip}/32"
                else
                    PALLOWEDIPS="${PALLOWEDIPS},${ip}/128"
                fi
            done
            PALLOWEDIPS="${PALLOWEDIPS#,}" # trim leading comma
            PALLOWEDIPS="${PALLOWEDIPS//,/, }" # add space after each comma
            # add peer's allowedips to server conf
            if [[ -n "${!SERVER_ALLOWEDIPS}" ]]; then
                echo "Adding ${!SERVER_ALLOWEDIPS} to wg0.conf's AllowedIPs for peer ${i}"
                cat <<DUDE >> /config/wg_confs/wg0.conf
AllowedIPs = ${PALLOWEDIPS}, ${!SERVER_ALLOWEDIPS}
DUDE
            else
                cat <<DUDE >> /config/wg_confs/wg0.conf
AllowedIPs = ${PALLOWEDIPS}
DUDE
            fi
            # add PersistentKeepalive if the peer is specified
            if [[ -n "${PERSISTENTKEEPALIVE_PEERS_ARRAY}" ]] && ([[ "${PERSISTENTKEEPALIVE_PEERS_ARRAY[0]}" = "all" ]] || printf '%s\0' "${PERSISTENTKEEPALIVE_PEERS_ARRAY[@]}" | grep -Fxqz -- "${i}"); then
                cat <<DUDE >> /config/wg_confs/wg0.conf
PersistentKeepalive = 25

DUDE
            else
                cat <<DUDE >> /config/wg_confs/wg0.conf

DUDE
            fi
            if [[ -z "${LOG_CONFS}" ]] || [[ "${LOG_CONFS}" = "true" ]]; then
                echo "PEER ${i} QR code (conf file is saved under /config/${PEER_ID}):"
                qrencode -t ansiutf8 < "/config/${PEER_ID}/${PEER_ID}.conf"
            else
                echo "PEER ${i} conf and QR code png saved in /config/${PEER_ID}"
            fi
            qrencode -o "/config/${PEER_ID}/${PEER_ID}.png" < "/config/${PEER_ID}/${PEER_ID}.conf"
        fi
    done
}

save_vars () {
    cat <<DUDE > /config/.donoteditthisfile
ORIG_SERVERURL="$SERVERURL"
ORIG_SERVERPORT="$SERVERPORT"
ORIG_PEERDNS="$PEERDNS"
ORIG_PEERS="$PEERS"
ORIG_ALLOCATED_RANGES="$ALLOCATED_RANGES"
ORIG_SERVER_INTERNAL_IP="$SERVER_INTERNAL_IP"
ORIG_ALLOWEDIPS="$ALLOWEDIPS"
ORIG_PERSISTENTKEEPALIVE_PEERS="$PERSISTENTKEEPALIVE_PEERS"
DUDE
}

if [[ -n "$PEERS" ]]; then
    echo "**** Server mode is selected ****"
    if [[ "$PEERS" =~ ^[0-9]+$ ]] && ! [[ "$PEERS" = *,* ]]; then
        mapfile -t PEERS_ARRAY < <(seq 1 "${PEERS}")
    else
        mapfile -t PEERS_ARRAY < <(echo "${PEERS}" | tr ',' '\n')
    fi
    if [[ -n "${PERSISTENTKEEPALIVE_PEERS}" ]]; then
        echo "**** PersistentKeepalive will be set for: ${PERSISTENTKEEPALIVE_PEERS/,/ } ****"
        mapfile -t PERSISTENTKEEPALIVE_PEERS_ARRAY < <(echo "${PERSISTENTKEEPALIVE_PEERS}" | tr ',' '\n')
    fi
    if [[ -z "$SERVERURL" ]] || [[ "$SERVERURL" = "auto" ]]; then
        SERVERURL=$(curl -s icanhazip.com)
        echo "**** SERVERURL var is either not set or is set to \"auto\", setting external IP to auto detected value of $SERVERURL ****"
    else
        echo "**** External server address is set to $SERVERURL ****"
    fi
    SERVERPORT=${SERVERPORT:-51820}
    echo "**** External server port is set to ${SERVERPORT}. Make sure that port is properly forwarded to port 51820 inside this container ****"
    echo "**** Server internal IP is set to ${SERVER_INTERNAL_IP} ****"
    ALLOCATED_RANGES=${ALLOCATED_RANGES:-10.13.13.3-10.13.13.255, fd42:42:42::3-fd42:42:42::ffff} # change default
    ALLOCATED_RANGES=${ALLOCATED_RANGES// /} # remove spaces just in case
    echo "**** Allocated ranges are set to $ALLOCATED_RANGES ****"
    ALLOWEDIPS=${ALLOWEDIPS:-0.0.0.0/0, ::/0}
    echo "**** AllowedIPs for peers $ALLOWEDIPS ****"
    if [[ -z "$PEERDNS" ]] || [[ "$PEERDNS" = "auto" ]]; then
        PEERDNS="${SERVER_INTERNAL_IP}"
        echo "**** PEERDNS var is either not set or is set to \"auto\", setting peer DNS to ${SERVER_INTERNAL_IP} to use wireguard docker host's DNS. ****"
    else
        echo "**** Peer DNS servers will be set to $PEERDNS ****"
    fi
    if [[ ! -f /config/wg_confs/wg0.conf ]]; then
        echo "**** No wg0.conf found (maybe an initial install), generating 1 server and ${PEERS} peer/client confs ****"
        generate_confs
        save_vars
    else
        echo "**** Server mode is selected ****"
        if [[ -f /config/.donoteditthisfile ]]; then
            . /config/.donoteditthisfile
        fi
        if [[ "$SERVERURL" != "$ORIG_SERVERURL" ]] || [[ "$SERVERPORT" != "$ORIG_SERVERPORT" ]] || [[ "$PEERDNS" != "$ORIG_PEERDNS" ]] || [[ "$PEERS" != "$ORIG_PEERS" ]] || [[ "$ALLOCATED_RANGES" != "$ORIG_ALLOCATED_RANGES" ]] || [[ "$ALLOWEDIPS" != "$ORIG_ALLOWEDIPS" ]] || [[ "$PERSISTENTKEEPALIVE_PEERS" != "$ORIG_PERSISTENTKEEPALIVE_PEERS" ]] || [[ "$SERVER_INTERNAL_IP" != "$ORIG_SERVER_INTERNAL_IP" ]]; then
            echo "**** Server related environment variables changed, regenerating 1 server and ${PEERS} peer/client confs ****"
            generate_confs
            save_vars
        else
            echo "**** No changes to parameters. Existing configs are used. ****"
        fi
    fi
else
    echo "**** Client mode selected. ****"
    USE_COREDNS="${USE_COREDNS,,}"
    printf %s "${USE_COREDNS:-false}" > /run/s6/container_environment/USE_COREDNS
fi

# set up CoreDNS
if [[ ! -f /config/coredns/Corefile ]]; then
    cp /defaults/Corefile /config/coredns/Corefile
fi

# let openresolv take control of resolv.conf
resolvconf -a control 2>/dev/null < /etc/resolv.conf
resolvconf -u

# permissions
lsiown -R abc:abc \
    /config
